### ISSUE TITLE
Error with Repeating decimal

### ISSUE THREAD

**Issue by phuctcw** [php-decimal/ext-decimal#15]
![chrome_2019-02-18_17-03-17](https://user-images.githubusercontent.com/35474294/52943370-8d99e300-339f-11e9-81a8-7e84b28c74ff.png)

**Comment by rtheunissen** [comment]
`(4/3)` will be a `float`, which is not a valid operand type. 

There is a `Rational` class in the 2.0 branch (unreleased, still testing) that would support what you are trying to achieve here, ie. `Rational::valueOf(4)->div(3)->mul(2)` would be `8/3`, which you can then convert to a decimal to whatever precision you require.

In this case, what you are seeing is expected behaviour.

2.0 is ready, I just have to update the documentation before I can publish it.
