### ISSUE TITLE
Usage with native PHP functions?

### ISSUE THREAD

**Issue by julienfalque** [php-decimal/ext-decimal#17]
The `Decimal` class does not seem to work very well with native PHP functions, e.g.:
```php
$foo = new Decimal('123.4567');
echo round($foo, 2); // 123
echo round((float) $foo, 2); // 123.46
```

I would expect both `round()` calls to return `123.46`, but it looks like the `Decimal` instance is casted to `int` when no explicit cast is done. Is this the expected behavior?

**Comment by rtheunissen** [comment]
HI @julienfalque, that is the expected behaviour for now. Unless we change (or somehow override) the internals of those functions, Decimal is not compatible. Those functions all assume either `int` or `float` so will attempt to cast whatever you pass to it. 

I would rather not override these core functions, so the best policy is to simply avoid all math or number-related functions unless you cast explicitly (for eg. `sin`).

**Comment by julienfalque** [comment]
Fair enough, thank you for your answer 👍
