### ISSUE TITLE
Allow operations between decimal and floats

### ISSUE THREAD

**Issue by marcospassos** [php-decimal/ext-decimal#19]
We are using the PHPDecimal library for a couple of months now, and the biggest issue we faced so far is the incompatibility between decimals and floats. Although in restrict contexts we (should) do not perform operations between float and decimal, there are some cases where this is desirable. The problem is that it is much easier to restrict where this should not happen than the other way around.

Because the class cannot handle floats, if you want this to be possible, you need to repeat the same boilerplate code everywhere:

```php
new Decimal (\is_float($number) ? (string) $number : $number);
```
Now, look how tedious it is to sum a list of numbers that includes decimal, integers and floats:
```php
/** @var array<int|float|Decimal> numbers **/
$sum = 0;
foreach ($numbers as $number) {
     if ($sum instanceof Decimal && \is_float($number)) {
         //...
     }

    if ($number instanceof Decimal && \is_float($sum)) {
         //...
    }

    $sum += $number;
}
````
...and for adding two numbers:
```php
if ($leftNumber instanceof Decimal && \is_float($rightNumber)) {
    return (float) $leftNumber->toString() + $rightNumber;
}

if ($rightNumber instanceof Decimal && \is_float($leftNumber)) {
    return $leftNumber + (float) $rightNumber->toString();
}

return $leftNumber + $rightNumber;
```

On the other hand, if one wants to ensure that floats cannot be added to decimals, it is better to disallow floats in the input using type hints or static analysis tools, which is much more efficient.

One may argue that you should not add floats to decimals and vice versa, but in some applications it is a legal operation.

In that sense, I'd like to propose to relax that constraint and allow not only creating a decimal from a float, but also operations involving floats.  A reasonable way to handle operations involving floats and decimal is converting the decimal operand to a float and then performing the operation. So, any operation between floats and decimals results in a float, the most inaccurate type between both. For edge cases, such as overflow and underflow, it should be consistent with PHP, where the result becomes `-+inf` and `0` respectively.

Although the former can be handled in a non-BC break way by introducing a named constructor such as `Decimal::fromValue()`, the latter requires a BC break.

**Comment by rtheunissen** [comment]
> One may argue that you should not add floats to decimals and vice versa, but in some applications it is a legal operation.

I agree that there may be circumstances where this is necessary/legal, but I believe that they should require an explicit conversion to communicate this intent. It is not about what is easier or nicer, but what is safer and would lead to code that is reliable. The cost of unintentionally using a float is a lot higher than the cost to explicitly specify that what you are doing is intentional.

`new Decimal (\is_float($number) ? (string) $number : $number);` is not ideal, but also does not have to be repeated as such. All you need is a helper function somewhere like this:

```php
function unsafe_decimal($number): Decimal
{
    return new Decimal (\is_float($number) ? (string) $number : $number);
}
```

**Comment by marcospassos** [comment]
@rtheunissen how about `Decimal::fromValue(float | string | Decimal $numeric)`?

**Comment by rtheunissen** [comment]
If anything, `Decimal::fromFloat(float $value, bool $exact = false)`, where exact as `false` would use the equivalent of a string cast, rather than the actual `double` value internally.

**Comment by marcospassos** [comment]
It looks like an elegant solution!

**Comment by marcospassos** [comment]
But it still requires the boilerplate code for creating a Decimal from a value that is either a `string`, `float` or `Decimal`.

**Comment by rtheunissen** [comment]
`Decimal::parse` maybe... but the philosophy has been to avoid floats for good reason. I worry that adding the ability to parse float out of the box would lead to that becoming the standard/most-common constructor. That's why a `parseFloat` type method communicates clearly that you are now using something non-standard, hopefully for good reason.

**Comment by marcospassos** [comment]
I understand, but IHMO the purpose of the library goes beyond just a replacement for floats. In our use case, we use it as in a proprietary DSL that has decimal native support, so interoperability with float and integers is very helpful.

**Comment by rtheunissen** [comment]
> In our use case, we use it as in a proprietary DSL that has decimal native support, so interoperability with float and integers is very helpful.

You should adapt for your use case then, I think. We can't accommodate them all, so this library will stay as pure as possible, so that other use cases can be served by composing packages that adapt to it. I think a `parseFloat` method is acceptable, though. Whatever boilerplate might be required to accept any type through the same API would need to be done externally to this lib, either internally in your DSL or as an external package. Could put it in the php-decimal org even, happy to do that. 👍 

That would also not require a `parseDecimal` method as part of the extension itself.

**Comment by marcospassos** [comment]
> You should adapt for your use case then, I think.
It's what we're doing already. Thank you anyway.

**Comment by rtheunissen** [comment]
> Because the class cannot handle floats, if you want this to be possible, you need to repeat the same boilerplate code everywhere

You shouldn't need to take `float` into account for every interaction like you are doing in your first comment. Could have your own Decimal class that wraps \Decimal\Decimal that hides it all away for you, or just a function that parses a Decimal from anything. 

```
function decimal($value, int $precision = Decimal::DEFAULT_PRECISION)
{
    if ($value instanceof Decimal) { 
        return $value;
    }

    return new Decimal(is_float($value) ? (string) $value : $value);
}
```
