### ISSUE TITLE
Please consider adding a toDecimalString function

### ISSUE THREAD

**Issue by hbgl** [php-decimal/ext-decimal#22]
Thanks for the great library. I use the library in conjunction with [PHP Money](https://github.com/moneyphp/money) which means that sometimes I need to convert a `Decimal` to `string` and pass it to the PHP `Money` object to perform calculations.

Example:
```
$decimal = new \Decimal\Decimal('0.0000001');
$tenMillionUsd = new \Money\Money('10000000', new \Money\Currency('USD'));
$oneUsd = $tenMillionUsd->multiply((string)$decimal); // throws
```
The problem is that converting `'0.0000001'` to `string` results in `'1E-7'` which the money object cannot parse. Of course I could write `$decimal->toFixed(Decimal::DEFAULT_PRECISION)` but it's verbose, easy to forget and produces a lot of trailing zeros. I think it would help a lot of people if there was a `toDecimalString` function which would always return a decimal string in decimal notation without any trailing zeros.

**Comment by rtheunissen** [comment]
What if `toFixed` defaults to the decimal instance's precision, rather than creating an entirely new method? The problem with `toFixed` though is that it will add trailing zeroes, so maybe a new method is necessary. `toDecimalString` is a bit ambiguous - not sure what format to expect. Maybe the string cast should always be equivalent to `toFixed` with the instance's precision, without trailing zeroes, and have a dedicated `toScientific` method?

**Comment by rtheunissen** [comment]
Quick update here, 2.0's `Decimal`'s `toString` returns a fixed representation in all cases, and `toSci` returns scientific notation regardless of the number. `Rational` (introduced in 2.0) `toString` returns a fractional representation, and `toSci` takes an optional precision parameter. Both have `toFixed(places)` as well. I believe this solves all the issues related to string representation.

**Comment by hbgl** [comment]
Hi rtheunissen. I also think that changing the existing `toString` function to always return the same format is the best course of action.  Thanks for the update.
