### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by VSG24** [php-decimal/ext-decimal#56]
It has almost been a year since the last release, when can we expect a new version with PHP 8+ support and bug fixes?

**Comment by zlodes** [comment]
I'm tried to add support for PHP8, but I need some help with tests.

There is a 1.x branch with PHP8 support: https://github.com/php-decimal/ext-decimal/pull/53

**Comment by rtheunissen** [comment]
Hi everyone, this is not a dead project. It has been difficult to find both the time and energy alongside my full time job, my research, a global pandemic, and a relocation to attend to my side projects. It weighs heavily on me that I have not been keeping my extensions at the cutting edge. This situation also illustrates the ineffectiveness of having a single maintainer on a project.  

Would anyone reading this be interested to learn about and help maintain the release of this project? I am taking some time off this week to resolve all my requests and critical open issues, starting with PHP8 support for ext-decimal, a new release, and then feature work and other discussions.

**Comment by maks-rafalko** [comment]
Hello @rtheunissen, hope you are well.

I'm sorry to ask it again, but could you please provide any approx. estimate about [PHP 8 Support](https://github.com/php-decimal/ext-decimal/pull/53), which is the main blocker for this repository right now.

We, consumers of this great `ext-decimal` project, would like to upgrade our applications to PHP 8, but it's impossible right now since `ext-decimal` doesn't work with it.

Is there anything we can help with here?

Your answer will help us decide whether we need to wait a bit more or probably move to some alternative solution. No pressure, just asking ;) 

Thank you in advance.

**Comment by carlonicora** [comment]
@maks-rafalko check my latest on #59 

PHP8 is currently supported in the branch `1.x-php8` and works like a charm

**Comment by rtheunissen** [comment]
Hi everyone, my goal for this weekend is to release both 1.x and 2.x with PHP8 support.

**Comment by rtheunissen** [comment]
v1.4.0 has been released with support for PHP 8 and mpdecial 2.5+
